# Generated by Django 2.1.5 on 2019-02-03 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='text',
            new_name='title',
        ),
        migrations.AddField(
            model_name='operation',
            name='body',
            field=models.TextField(default='testing'),
            preserve_default=False,
        ),
    ]
