# Generated by Django 2.1.5 on 2019-02-03 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20190203_0400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.TextField(max_length=50)),
                ('lastname', models.TextField(max_length=50)),
                ('operation', models.TextField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='operation',
            name='title',
            field=models.TextField(max_length=50),
        ),
    ]
