# Generated by Django 2.1.5 on 2019-02-03 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20190203_0420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.TextField(max_length=50)),
                ('category', models.TextField(max_length=50)),
                ('url', models.URLField()),
                ('justificaiton', models.TextField(max_length=250)),
                ('time', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Mark',
        ),
        migrations.AddField(
            model_name='operation',
            name='name',
            field=models.TextField(default='', max_length=75),
            preserve_default=False,
        ),
    ]
