# Generated by Django 2.1.5 on 2019-02-03 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20190203_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='intel',
            name='title',
            field=models.TextField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
