# Generated by Django 2.1.5 on 2019-02-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_tools'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intel',
            name='justificaiton',
        ),
        migrations.AddField(
            model_name='intel',
            name='reason',
            field=models.TextField(default='', max_length=600),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='intel',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='intel',
            name='operation',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='intel',
            name='title',
            field=models.CharField(max_length=25),
        ),
    ]
